
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://rachelleffel.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: '/techyes'

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Rachel Leffel"
title: "TechYes!"
description: "TechYes! Diversity in Tech Meetup site"
keywords: "meetup, diversity, tech"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/techyeslogo.png"

background-img: "../img/pinkgradient.png"

##############################
# Dynamic Text on the Header #
##############################

#dynamic-typing: True
#shuffle: True # Shuffle the lines.
#loop: True
#loop-count: False # Set False for infinite loop, or set any number for finite loop.
#type-speed: 10
#start-delay: 200
#delete-delay: 5000
#lines: # You can add HTML Tags in the Text
#  - text: "The lower you fall, the higher you'll fly."
#  - text: "Whereâ€™s your will to be weird?"

me-img: "/img/techyeslogo.png"

##############################
# Color the browser elements #
##############################
color-browser: "#F7F7F7"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 1000

paginate: 5

email-share: False
fb-share: False
twitter-share: False
linkedin-share: False
reddit-share: False
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

syntax-highlight: True

############
# Timeline #
############

nyc_events:
  - image: "/img/timeline/NYCEvent8.png"
    description: "TechYes! #8: Let's Blaze! (trails)"
    date: "New York City &#124; April 27, 2017"
  - image: "/img/timeline/NYCEvent7.png"
    description: "TechYes! #7: The Diversity in the Data"
    date: "New York City &#124; March 1, 2017"
  - image: "/img/timeline/NYCEvent6.png"
    description: "TechYes! #6: The Politics of Treating People Well"
    date: "New York City &#124; December 14, 2016"
  - image: "/img/timeline/NYCEvent5.png"
    description: "TechYes! #5: Jamboree!"
    date: "New York City &#124; October 19, 2016"
  - image: "/img/timeline/NYCEvent4.png"
    description: "TechYes! #4: Beyond the Basic Background"
    date: "New York City &#124; August 4, 2016"
  - image: "/img/timeline/NYCEvent3.png"
    description: "TechYes! #3: Bias (Un)Fair"
    date: "New York City &#124; August 4, 2016"
  - image: "/img/timeline/NYCEvent2.png"
    description: "TechYes! #2: Diversity in Action"
    date: "New York City &#124; August 4, 2016"
  - image: "/img/timeline/NYCEvent1.png"
    description: "TechYes! #1: Initial Commit"
    date: "New York City &#124; August 4, 2016"

sf_events:
  - image: "/img/timeline/SFEvent2.png"
    description: "TechYes! #1: Initial Commit"
    date: "San Francisco &#124; March 22, 2017"
  - image: "/img/timeline/SFEvent1.png"
    description: "i am a test! also, reinstall jemoji~"
    date: "San Francisco &#124; May 23, 2016"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"


############
# 404 page #
############

err-404-img: "/img/techyeslogo.png"

##################
# GPG on Keybase #
##################

keybase-username: johnsmith
keybase-in-social: True
keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  # About: 'about'
  Blog: 'latest-post'
  # Contact: 'contact'
  # Timeline: 'timeline'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]
keep_files: ["includes/img/lucia.png", "includes/img/rachel.jpg", "includes/img/allison.jpg", "includes/img/adeola.jpg"]
include: ["includes/img", includes/img/lucia.png", "includes/img/rachel.jpg", "includes/img/allison.jpg", "includes/img/adeola.jpg"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate