  
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://rachelleffel.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: '/techyes'

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Rachel Leffel"
title: "TechYes!"
description: "TechYes! Diversity in Tech Meetup site"
keywords: "meetup, diversity, tech"
favicon: "/img/web-app/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/techyeslogo.png"

background-img: "../img/pinkgradient.png"

##############################
# Dynamic Text on the Header #
##############################

#dynamic-typing: True
#shuffle: True # Shuffle the lines.
#loop: True
#loop-count: False # Set False for infinite loop, or set any number for finite loop.
#type-speed: 10
#start-delay: 200
#delete-delay: 5000
#lines: # You can add HTML Tags in the Text
#  - text: "The lower you fall, the higher you'll fly."
#  - text: "Where’s your will to be weird?"

me-img: "/img/techyeslogo.png"

##############################
# Color the browser elements #
##############################
color-browser: "#F7F7F7"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 1000

paginate: 5

email-share: False
fb-share: False
twitter-share: False
linkedin-share: False
reddit-share: False
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

syntax-highlight: True

############
# Timeline #
############

nyc_events:
  - image: "/img/timeline/NYCEvent8.png"
    description: "TechYes #9: Check Yourself Before You Wreck Yourself (emotionally)"
    date: "New York City &#124; June 28, 2017"
    paragraph: "Something goes here"  
  - image: "/img/timeline/NYCEvent8.png"
    description: "TechYes! #8: Let's Blaze! (trails)"
    date: "New York City &#124; April 27, 2017"
    paragraph: "Something goes here"
  - image: "/img/timeline/NYCEvent7.png"
    description: "TechYes! #7: The Diversity in the Data"
    date: "New York City &#124; March 1, 2017"
    paragraph: "Something goes here"
  - image: "/img/timeline/NYCEvent6.png"
    description: "TechYes! #6: The Politics of Treating People Well"
    date: "New York City &#124; December 14, 2016"
    paragraph: "Something goes here"
  - image: "/img/timeline/NYCEvent5.png"
    description: "TechYes! #5: Jamboree!"
    date: "New York City &#124; October 19, 2016"
    paragraph: "Something goes here"
  - image: "/img/timeline/NYCEvent4.png"
    description: "TechYes! #4: Beyond the Basic Background"
    date: "New York City &#124; August 4, 2016"
    paragraph: "Something goes here"
  - image: "/img/timeline/NYCEvent3.png"
    description: "TechYes! #3: Bias (Un)Fair"
    date: "New York City &#124; August 4, 2016"
    paragraph: "Something goes here"
  - image: "/img/timeline/NYCEvent2.png"
    description: "TechYes! #2: Diversity in Action"
    date: "New York City &#124; August 4, 2016"
    paragraph: "Something goes here"
  - image: "/img/timeline/NYCEvent1.png"
    description: "TechYes! #1: Initial Commit"
    date: "New York City &#124; August 4, 2016"
    paragraph: "Something goes here"
  - image: "/img/timeline/default.png"
    description: 
    date: 
    paragraph: "Something goes here"    

sf_events:
  - image: "/img/timeline/SFEvent2.png"
    description: "TechYes! Meet-Up #3: Behaviors of Inclusion"
    date: "San Francisco &#124; July 31, 2017"
    paragraph: "Something goes here"
  - image: "/img/timeline/SFEvent2.png"
    description: "TechYes! Meet-Up #2: The Personal Side of Data"
    date: "San Francisco &#124; March 22, 2017"
    paragraph: "Something goes here"
  - image: "/img/timeline/SFEvent1.png"
    description: "TechYes! Meetup #1: Initial Commit"
    date: "San Francisco &#124; May 23, 2016"
    paragraph: "Something goes here"


nyc_upcoming:
  - image: 
    description: "<h3>Upcoming events in <span style='color:#009AD1;'>New York City</span></h3>
    <h4>TechYes! #9: Check Yourself Before You Wreck Yourself (emotionally)</h4>"
    date: "<span style='color:#009AD1;'>When:</span> Wednesday, June 28, 2017 <br>
    <span style='color:#009AD1;'>Where:</span> Greenhouse Software, 110 5th, 3rd Fl
New York, NY 10011"
    paragraph: |
      Ever dive into a conversation about topics rooted in diversity, inclusion, and your personal experiences and have it go from real casual to emotionally charged? Maybe you were talking to your manager during a 1:1. Perhaps it was your distant relative at some family reunion. Regardless of the situation, some conversations and experiences inevitably come with a slew of emotions that are sometimes difficult to process. How can we check on our range of emotions and process them so that they help instead of hinder?
      
      We're excited to announce that we're partnering with LifeLabs Learning to provide you with a workshop on regulating emotions!
      
      This workshop will be taught by Tania Luna, Partner & Facilitator at LifeLabs Learning. Tania specializes in organizational psychology, emotion regulation, and surprise psychology. She is a leadership trainer, researcher, TED speaker, and co-author of the book Surprise: Embrace the Unpredictable & Engineer the Unexpected. 
      
      Our friends at Jopwell are hosting the event! 
      
      Jopwell helps Black, Latino/Hispanic, and Native American students and professionals unlock opportunities for career advancement, not only when looking for a job but at all career stages. Jopwell’s mission is twofold: Make a substantial, measurable impact on increasing Black, Latino/Hispanic, and Native American representation and to facilitate a national dialogue about diversity in the workplace. Sign up to get connected with top opportunities.
      
      As always, dinner and drinks will be served at 6:30pm. We'll start the official event at 7:00pm. Can't wait to see you all there!"

sf_upcoming:
  - image: 
    description: "<h3>Upcoming events in <span style='color:#20B2AA;'>San Francisco</span></h3>
    <h4>No upcoming events</h4>"
    date: 
    paragraph: 

# First image of the Timeline

timeline-img: "/img/timeline/default.png"


############
# 404 page #
############

err-404-img: "/img/techyeslogo.png"

##################
# GPG on Keybase #
##################

keybase-username: johnsmith
keybase-in-social: True
keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  # About: 'about'
  Blog: 'latest-post'
  # Contact: 'contact'
  # Timeline: 'timeline'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]
keep_files: ["includes/img/lucia.png", "includes/img/rachel.jpg", "includes/img/allison.jpg", "includes/img/adeola.jpg"]
include: ["includes/img", includes/img/lucia.png", "includes/img/rachel.jpg", "includes/img/allison.jpg", "includes/img/adeola.jpg"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
